const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Text.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY
	];
};
self.C3_JsPropNameTable = [
	{平台: 0},
	{視野跟隨: 0},
	{閃爍: 0},
	{ofeina: 0},
	{實體: 0},
	{Sprite2: 0},
	{平鋪背景: 0},
	{鍵盤: 0},
	{Sprite3: 0},
	{滑鼠: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Text: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{音頻: 0},
	{護罩: 0},
	{互燈: 0},
	{護條: 0},
	{Sprite: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{旋轉: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{與: 0},
	{十: 0},
	{星: 0},
	{Sprite33: 0},
	{流: 0},
	{恕: 0},
	{Sprite34: 0},
	{Text2: 0},
	{Sprite35: 0},
	{開始: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{斬: 0},
	{跳: 0},
	{跳2: 0},
	{斬2: 0},
	{瞬移中他媽別按啦: 0},
	{砍的狀態其他別吵啦: 0},
	{別她媽亂砍啦: 0},
	{血量啦: 0},
	{回血啦: 0},
	{回血冷卻用啦: 0},
	{大砲啦: 0},
	{大泡泡冷卻OWO: 0},
	{護數: 0},
	{護啦: 0},
	{boss血: 0},
	{別他媽閃了: 0},
	{boss防禦: 0},
	{雨: 0},
	{節末: 0},
	{流星: 0},
	{手手: 0},
	{手手冷卻: 0},
	{十字: 0},
	{十字冷卻: 0},
	{死法: 0},
	{背景: 0},
	{開始了別叫: 0},
	{真開始啦: 0},
	{他快掛了QAQ: 0},
	{砍攻擊傷害: 0},
	{矩攻擊傷害: 0}
];

self.InstanceType = {
	ofeina: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	平鋪背景: class extends self.ITiledBackgroundInstance {},
	鍵盤: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	滑鼠: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	護罩: class extends self.ISpriteInstance {},
	互燈: class extends self.ISpriteInstance {},
	護條: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	與: class extends self.ITextInstance {},
	十: class extends self.ITextInstance {},
	星: class extends self.ITextInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	流: class extends self.ITextInstance {},
	恕: class extends self.ITextInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	開始: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {}
}